"""Thin, deterministic boundary around the public ``edgartools`` package."""

from mortgage_servicing_dashboard.edgartools_adapter.adapter import EdgarToolsAdapter
from mortgage_servicing_dashboard.edgartools_adapter.backend import FilingDateFilter
from mortgage_servicing_dashboard.edgartools_adapter.bootstrap import (
    EdgarBootstrap,
    EdgarBootstrapConfig,
)
from mortgage_servicing_dashboard.edgartools_adapter.dto import (
    AcquiredContent,
    Attachment,
    AttachmentAcquisition,
    CalculationArc,
    Company,
    CompanyFactCandidate,
    CompanyFactsDiscovery,
    ContentRepresentation,
    DefinitionArc,
    Filing,
    FilingStructure,
    LinkbaseArc,
    PresentationArc,
    RawMetadata,
    RetainedContent,
    ViewerIssueClassification,
    ViewerReport,
    ViewerValidationIssue,
    XbrlContext,
    XbrlDimension,
    XbrlFact,
    XbrlFiling,
    XbrlFootnote,
    XbrlUnit,
)
from mortgage_servicing_dashboard.edgartools_adapter.errors import (
    AdapterConfigurationError,
    AdapterIdentityError,
    AdapterIntegrityError,
    AdapterLibraryError,
    AdapterNotFoundError,
    AdapterParsingError,
    AdapterRateLimitError,
    AdapterSelectionError,
    AdapterState,
    AdapterTransportError,
    AdapterValidationError,
    EdgarToolsAdapterError,
    map_edgar_exception,
)

__all__ = [
    "AcquiredContent",
    "AdapterConfigurationError",
    "AdapterIdentityError",
    "AdapterIntegrityError",
    "AdapterLibraryError",
    "AdapterNotFoundError",
    "AdapterParsingError",
    "AdapterRateLimitError",
    "AdapterSelectionError",
    "AdapterState",
    "AdapterTransportError",
    "AdapterValidationError",
    "Attachment",
    "AttachmentAcquisition",
    "CalculationArc",
    "Company",
    "CompanyFactCandidate",
    "CompanyFactsDiscovery",
    "ContentRepresentation",
    "DefinitionArc",
    "EdgarBootstrap",
    "EdgarBootstrapConfig",
    "EdgarToolsAdapter",
    "EdgarToolsAdapterError",
    "Filing",
    "FilingDateFilter",
    "FilingStructure",
    "LinkbaseArc",
    "PresentationArc",
    "RawMetadata",
    "RetainedContent",
    "ViewerIssueClassification",
    "ViewerReport",
    "ViewerValidationIssue",
    "XbrlContext",
    "XbrlDimension",
    "XbrlFact",
    "XbrlFiling",
    "XbrlFootnote",
    "XbrlUnit",
    "map_edgar_exception",
]
